language: python
python:
    - "2.7"

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci Sensor_Box/main.cpp --board=frdm_kl25z --lib="Sensor_Box/nRF24L01P" --lib="Sensor_Box/MMA8451Q"
